### PR TITLE
fix failures on 1.7

### PR DESCRIPTION
**Pull request by simeonschaub**

### CODE REVIEW

**Review by vchuravy — COMMENTED** [review]
Thanks @simeonschaub 

@bors r+

**Comment by vchuravy** [comment]
Ah the issue here is that we actually did want to change the `kw` to assignment.

**Comment by simeonschaub** [comment]
Ah, sorry. Didn't run the whole test suite, only my minimal example.

**Comment by vchuravy** [comment]
yeah so the issue is that the `esc` on the rhs could see a constant intead of a variable.

```
julia> esc(1)
:($(Expr(:escape, 1)))
```

seems to be valid, but aparently not in the context the value gets then used?

**Comment by vchuravy** [comment]
The original error is:

```
ERROR: LoadError: syntax: invalid syntax (escape 1)
Stacktrace:
 [1] top-level scope
   @ ~/work/KernelAbstractions.jl/KernelAbstractions.jl/test/compiler.jl:40
 [2] include(mod::Module, _path::String)
   @ Base ./Base.jl:417
 [3] include(x::String)
   @ Main.Testsuite ~/work/KernelAbstractions.jl/KernelAbstractions.jl/test/testsuite.jl:1
 [4] top-level scope
   @ ~/work/KernelAbstractions.jl/KernelAbstractions.jl/test/testsuite.jl:14
 [5] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [6] top-level scope
   @ ~/work/KernelAbstractions.jl/KernelAbstractions.jl/lib/CUDAKernels/test/runtests.jl:6
 [7] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [8] top-level scope
   @ none:6
in expression starting at /home/runner/work/KernelAbstractions.jl/KernelAbstractions.jl/test/compiler.jl:40
in expression starting at /home/runner/work/KernelAbstractions.jl/KernelAbstractions.jl/test/testsuite.jl:1
in expression starting at /home/runner/work/KernelAbstractions.jl/KernelAbstractions.jl/lib/CUDAKernels/test/runtests.jl:6
```

**Comment by simeonschaub** [comment]
The issue was that https://github.com/JuliaLang/julia/pull/41040 added escaping in `gen_call_with_extracted_types_and_kwargs`, so kwargs were escaped twice.

**Pull request merged**
