### PR TITLE
ROCKernels: Update to AMDGPU 0.4

### PR DESCRIPTION
**Pull request by jpsamaroo**

### CODE REVIEW

**Comment by vchuravy** [comment]
Needs to update the Project.toml?

**Comment by jpsamaroo** [comment]
> Needs to update the Project.toml?

Somehow it missed the push...

So now we have a `ROCDevice` in AMDGPU.jl. What should we do with `ROCKernels.ROCDevice`? Any ideas for a better name?

**Comment by jpsamaroo** [comment]
I switched to `KAROCDevice` in the meantime. Let me know if anyone has better name ideas :smile:

**Comment by jpsamaroo** [comment]
What's up with the MPI failures?

**Comment by vchuravy** [comment]
`KAROCDevice` reads absolutly horrid. You also need to update ROCKernels to 0.4 since this is a breaking change.  Maybe `ROCmDevice`? Can we cheat and just re-use `ROCDevice` from `AMDGPU.jl`

**Comment by jpsamaroo** [comment]
> Maybe ROCmDevice? Can we cheat and just re-use ROCDevice from AMDGPU.jl

But it would need to be `<: GPU`, no?

**Comment by vchuravy** [comment]
I don't think we use that dispatch rule for much...

**Comment by vchuravy** [comment]
Can you remove the Manidest.toml you added?

**Comment by jpsamaroo** [comment]
@vchuravy the `<: GPU` is necessary to get `<: Device` dispatches. Would it be reasonable to manually forward these for `ROCDevice`?

**Comment by vchuravy** [comment]
Sure!

**Comment by jpsamaroo** [comment]
Ok, now all calls generated by the `@kernel` macro forward down to `KernelAbstractions.construct`, which is defined for `::Device`, and ROCKernels defines its own for `::ROCDevice`.

**Review by leios — APPROVED** [review]
It seems to run for me locally. The MPI errors seem to be a general CI problem right now?

**Comment by jpsamaroo** [comment]
Yeah, the MPI failures seem to be something specific to CI.

Let's hold off on merging this until:
- We've tested that this works properly for CUDAKernels (since we change some internals to support using `AMDGPU.ROCDevice`
- We've added the `ROCDevice()` ctor to AMDGPU, so that we can keep doing that (it's much nicer for users)

**Pull request merged**
