### PR TITLE
Fix Bors

### PR DESCRIPTION
**Pull request by DilumAluthge**
Script used to generate the list of statuses: https://github.com/JuliaGPU/KernelAbstractions.jl/blob/master/.ci/bin/get-github-status-list.jl

### CODE REVIEW

**Comment by DilumAluthge** [comment]
bors mrge

**Comment by DilumAluthge** [comment]
bors merge

**Comment by DilumAluthge** [comment]
bors merge

**Comment by jpsamaroo** [comment]
I suspect AMDGPU has a race during kernel launch that causes us to sometimes not write out kernel packets correctly; usually restarting CI fixes it (as you can see from the now-passing ROCM tests). I'll file an issue for it.

**Pull request merged**
