### PR TITLE
fix on nightly

### PR DESCRIPTION
**Pull request by simeonschaub**

### CODE REVIEW

**Comment by simeonschaub** [comment]
(I didn't run the full test suite locally, so would be good to run some kind of CI on this first)

**Comment by vchuravy** [comment]
bors try

**Comment by vchuravy** [comment]
Thanks!

**Comment by DilumAluthge** [comment]
Buildkite is still failing on nightly.

**Comment by DilumAluthge** [comment]
https://buildkite.com/julialang/kernelabstractions-dot-jl/builds/63

**Comment by simeonschaub** [comment]
Is BuildKite using CUDA master?

**Comment by DilumAluthge** [comment]
It is using CUDA.jl version 2.3.0.

**Comment by simeonschaub** [comment]
I think the latest release doesn't work on nightly yet, only the current master

**Comment by DilumAluthge** [comment]
CI tests are also failing on 1.6-nightly. Is that the same issue?

A643E80C-FA24-45E9-9A9E-C27166936F45

**Comment by simeonschaub** [comment]
Yes, I think that's the same issue

**Comment by vchuravy** [comment]
Yes we need a CUDA.jl release since we can't do Manifest based development here.

**Comment by DilumAluthge** [comment]
BTW I can confirm that using the master branch of CUDA.jl fixes the KernelAbstractions Buildkite on Julia 1.6-nightly and Julia nightly.

1B88727C-CAD1-407D-8855-74961382679E

**Comment by DilumAluthge** [comment]
Once we have a new release of CUDA.jl, I'll switch those two Buildkite jobs back to using the registered version of CUDA.jl.

**Pull request merged**
