### PR TITLE
Transition from Travis CI to GitHub Actions CI

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Since this repository uses Bors, I have configured GitHub Actions to only run on pushes to the `master`, `staging`, and `trying` branches.

**Comment by DilumAluthge** [comment]
@vchuravy Can you `bors try` on this PR?

**Comment by vchuravy** [comment]
bors try

**Comment by DilumAluthge** [comment]
Soooo... Buildkite does run on the `trying` branch! Which is good. But presumably you want it to run on both `staging` and `trying`.

**Pull request merged**
