### PR TITLE
[EnzymeExt] handle active vars to kernels

### PR DESCRIPTION
**Pull request by wsmoses**

### CODE REVIEW

**Comment by wsmoses** [comment]
Requires https://github.com/EnzymeAD/Enzyme.jl/pull/1160

**Comment by vchuravy** [comment]
Needs tests

**Comment by wsmoses** [comment]
It has a test (the square_caller one unless that didn't upload)

**Comment by wsmoses** [comment]
@vchuravy I just released the requisite EnzymeCore patch, so this is ready for review

**Pull request merged**
