### PR TITLE
Allow empty return statements

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by eschnett** [comment]
Closes https://github.com/JuliaGPU/KernelAbstractions.jl/issues/443.

**Comment by pxl-th** [comment]
Does it allow multiple return statements?

```julia
function ker()
    ...
    if something()
       return
    end
    ...
    if something_else()
       return
    end
    ...
    return
end
```

**Comment by eschnett** [comment]
It does. But – should it?

**Comment by pxl-th** [comment]
I'd like to have this option. Right now I find myself writing wrapper functions that I call from the kernel just to be able to use return statements.

**Comment by eschnett** [comment]
*ping* Could you let the CI workflows run for this PR?

**Review by pxl-th — APPROVED** [review]

**Pull request merged**
