### PR TITLE
Add the Buildkite status badges, and fix the Bors config

### LINKED ISSUE #158: Add Buildkite status badge to the KernelAbstractions.jl README?
As far as I can tell, Buildkite provides README status badges (similar to the status badges provided by Travis, AppVeyor, GitHub Actions, etc.): https://buildkite.com/docs/integrations/build-status-badges

It would be great to add the Buildkite status badge to the KernelAbstractions.jl README.

### LINKED ISSUE #159: bors.toml: use Buildkite status(es) instead of GitLab statuses?
Currently, the `bors.toml` file says this:
https://github.com/JuliaGPU/KernelAbstractions.jl/blob/9d7a788054a03b882ea6d47e94ce390dd1247245/bors.toml#L1-L4

But, if I understand correctly, this repo now uses Buildkite for the GPU tests (not GitLab). Is that correct? If so, `bors.toml` line 2 (the line that says `"ci/gitlab/%", `) should be changed to use the Buildkite status(es) instead of the GitLab statuses.

### PR DESCRIPTION
**Pull request by DilumAluthge**
Fixes #158 
Fixes #159

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Here's what it looks like:

Screen Shot 2020-12-15 at 16 58 24

**Comment by vchuravy** [comment]
Thanks!

**Comment by DilumAluthge** [comment]
@vchuravy Just FYI, Buildkite is not running on the Bors `staging` branch. Is this intentional?

**Comment by vchuravy** [comment]
> Is this intentional?

No it isn't :)

**Comment by DilumAluthge** [comment]
Buildkite does run on the `master` branch, so the question is: do you also want Buildkite to run on `bors r+`s, or do you only want Buildkite to run on `master`?

**Comment by DilumAluthge** [comment]
> > Is this intentional?
> 
> No it isn't :)

Hmmm.

**Comment by DilumAluthge** [comment]
Disregard what I said - Buildkite is in fact running on the `staging` branch.

**Comment by DilumAluthge** [comment]
I think we need to update the Bors config for Buildkite and GHA/

**Comment by DilumAluthge** [comment]
@vchuravy Alright try to merge now. Bors is now set up to look for GHA and Buildkite.

**Comment by DilumAluthge** [comment]
Oh I know how to fix this.

**Comment by DilumAluthge** [comment]
Hmm. Actually I'm not sure.

**Comment by DilumAluthge** [comment]
Alright, here are ALL of the statuses:
```
5-element Vector{String}:
 "bors"
 "buildkite/kernelabstractions-dot-jl"
 "buildkite/kernelabstractions-dot-jl/julia-1-dot-5"
 "buildkite/kernelabstractions-dot-jl/julia-nightly"
 "buildkite/kernelabstractions-dot-jl/pipeline"
```

And here are ALL of the GitHub checks:
```
17-element Vector{String}:
 "CI (1, macOS-latest, x64)"
 "CI (1, ubuntu-latest, x64)"
 "CI (1, windows-latest, x64)"
 "CI (1.3, macOS-latest, x64)"
 "CI (1.3, ubuntu-latest, x64)"
 "CI (1.3, windows-latest, x64)"
 "CI (1.4, macOS-latest, x64)"
 "CI (1.4, ubuntu-latest, x64)"
 "CI (1.4, windows-latest, x64)"
 "CI (1.5, macOS-latest, x64)"
 "CI (1.5, ubuntu-latest, x64)"
 "CI (1.5, windows-latest, x64)"
 "CI-julia-nightly (nightly, macOS-latest, x64)"
 "CI-julia-nightly (nightly, ubuntu-latest, x64)"
 "CI-julia-nightly (nightly, windows-latest, x64)"
 "Doctests"
 "Documentation"
```

**Comment by DilumAluthge** [comment]
bors try

**Comment by DilumAluthge** [comment]
bors try

**Pull request merged**
